engines:
  csslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false	
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
  - "**.css"
exclude_paths:
- source/Salt/**/*
